import { Annotation } from '@langchain/langgraph';

/**
 * Defines the state channels for the LangGraph execution.
 * 
 * company: The input company name string.
 * research: The structured research data gathered by the Research Node.
 * analysis: The synthesized evaluation generated by the Analysis Node.
 * recommendation: The final binary decision (INVEST/PASS).
 * confidence: The integer confidence score (0-100).
 * reasoning: An array of strings justifying the decision.
 * status: A tracking string to monitor which node is currently active.
 */
export const GraphState = Annotation.Root({
  company: Annotation(),
  research: Annotation({
    reducer: (x, y) => y,
    default: () => ({})
  }),
  analysis: Annotation({
    reducer: (x, y) => y,
    default: () => ({})
  }),
  recommendation: Annotation({
    reducer: (x, y) => y,
    default: () => ""
  }),
  confidence: Annotation({
    reducer: (x, y) => y,
    default: () => 0
  }),
  reasoning: Annotation({
    reducer: (x, y) => y,
    default: () => []
  }),
  executionTime: Annotation({
    reducer: (x, y) => y,
    default: () => 0
  }),
  status: Annotation({
    reducer: (x, y) => y,
    default: () => ""
  })
});
